=== Amineharoun3/cv24v1/src/main/resources/xsd/cv24.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
           targetNamespace="http://univ.fr/cv24"
           xmlns:cv24="http://univ.fr/cv24"
           elementFormDefault="qualified">

    <xs:element name="cv24">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="id" type="xs:int"/>
                <xs:element name="identite">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="genre" type="xs:string"/>
                            <xs:element name="prenom" type="xs:string"/>
                            <xs:element name="nom" type="xs:string"/>
                            <xs:element name="phone" type="xs:string"/>
                            <xs:element name="mail" type="xs:string"/>
                            <xs:element name="date_naissance" type="xs:date"/>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
                <xs:element name="objectif" type="xs:string"/>
                <xs:element name="diplome" type="xs:string"/>
                <xs:element name="poste_recherche" type="xs:string"/>
                <xs:element name="certificats" type="xs:string"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== Amineharoun3/cv24v1/src/main/resources/cv24.xml
<?xml version="1.0" encoding="UTF-8"?>
<cv24:cv24 xmlns:cv24="http://univ.fr/cv24" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://univ.fr/cv24 /xsd/cv24.xsd">
    <cv24:id>8</cv24:id>
    <cv24:identite>
        <cv24:genre>Mascul</cv24:genre>
        <cv24:prenom>Ane</cv24:prenom>
        <cv24:nom>Haron</cv24:nom>
        <cv24:phone>0087</cv24:phone>
        <cv24:mail>aeroun@gmail.com</cv24:mail>
        <cv24:date_naissance>1985-12-30</cv24:date_naissance>
    </cv24:identite>
    <cv24:objectif>DI/CD</cv24:objectif>
    <cv24:diplome>Mas SSI-GIL</cv24:diplome>
    <cv24:poste_recherche>Analyste-programmeur</cv24:poste_recherche>
    <cv24:certificats>Certificat en analyse et conception</cv24:certificats>
</cv24:cv24>
